---
title: "p8105_hw2_yl5214"
output: github_document
---

```{r}
library(tidyverse)
```

Question 2
Read and clean the Mr. Trash Wheel sheet
```{r}
Mr_trash_df =
  readxl::read_excel('data/202309 Trash Wheel Collection Data.xlsx', sheet = 1, range = "A2:N586" ) |> 
  mutate( trash_wheel= 'Mr_trash_wheel') |> 
 janitor::clean_names() |> 
  select(-month, -year) |> 
  mutate(
    homes_powered = weight_tons*500/30
  ) |> 
  pivot_longer(
    plastic_bottles:sports_balls,
    names_to  = 'trash',
    values_to = 'number'
  ) |> 
  relocate(dumpster, date, trash, number)

```
Import, clean, and organize the data for Professor Trash Wheel and Gwynnda
```{r}
professor_trash_df =
  readxl::read_excel('data/202309 Trash Wheel Collection Data.xlsx', sheet = 2, range = "A2:M108" ) |> 
  mutate( trash_wheel= 'professor_trash_wheel') |> 
 janitor::clean_names() |> 
  select(-month, -year) |> 
  mutate(
    homes_powered = weight_tons*500/30
  ) |> 
   pivot_longer(
    plastic_bottles:wrappers,
    names_to  = 'trash',
    values_to = 'number'
  ) |> 
  relocate(dumpster, date, trash, number)

gwynnda_df =
  readxl::read_excel('data/202309 Trash Wheel Collection Data.xlsx', sheet = 4, range = "A2:L157" ) |>
  mutate( trash_wheel= 'gwynnda_trash_wheel') |>
 janitor::clean_names() |> 
  select(-month, -year) |> 
  mutate(
    homes_powered = weight_tons*500/30
  )|> 
   pivot_longer(
    plastic_bottles:wrappers,
    names_to  = 'trash',
    values_to = 'number'
  ) |> 
  relocate(dumpster, date, trash, number)

```

Combine these with the Mr. Trash Wheel dataset to produce a single tidy dataset
```{r}
combine_df =
  bind_rows(Mr_trash_df, professor_trash_df, gwynnda_df) |> 
  janitor::clean_names() |> 
relocate(trash_wheel)
```








